### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by tinycaster** [CTK-WARRIOR/Anime-Hub#5]
Hello CTK, Do you have a license for this software?
I recomment have one, you can get a license here: [https://choosealicense.com](https://choosealicense.com/)

**Comment by PaimonWheeWhee** [comment]
MIT license please :D

**Comment by CTK-WARRIOR** [comment]
Nope, no license : )

**Comment by tinycaster** [comment]
lmao

**Comment by Yonle** [comment]
Lmao

**Comment by PaimonWheeWhee** [comment]
No license means that anyone can take the code right

**Comment by Yonle** [comment]
Ye. They can make their own license kek
